name: demo
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - bokeh
  - bqplot
  - importnb
  - ipympl
  - ipywidgets >=7
  - jupyterlab >=0.35,<0.36
  - nbconvert
  - nodejs
  - pyqt >=5.9,<6
  - python >=3.7,<3.8
  - pythreejs
  - tornado <6
